/*
 * utf_tables.h — DFA table declarations for Unicode processing.
 *
 * THIS FILE IS GENERATED by the gen/ pipeline tools.
 * DO NOT EDIT — changes will be overwritten.
 *
 * DFA execution model:
 *   Feed bytes to the DFA one at a time.  When it reaches an accepting
 *   state, the state index encodes either "identity" (no change) or an
 *   index into the OTT (output text table).  OTT entries are either
 *   literal replacements or XOR masks.
 *
 * Table naming convention:
 *   <name>_itt[256]   Input Translation Table (byte -> column index)
 *   <name>_sot[N]     State Offset Table (state -> offset into SBT)
 *   <name>_sbt[M]     State Byte Table (compressed transition matrix)
 *   <name>_ott[K]     Output Text Table (replacement strings, for transforms)
 */

#ifndef UTF_TABLES_H
#define UTF_TABLES_H

#include "utf_types.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ---- Case mapping DFAs ---- */

/* utf/tr_tolower.txt: 1460 code points, 62 states, 87 columns */
#define TR_TOLOWER_START_STATE (0)
#define TR_TOLOWER_ACCEPTING_STATES_START (62)
extern UTF_API const unsigned char  tr_tolower_itt[256];
extern UTF_API const unsigned short tr_tolower_sot[62];
extern UTF_API const unsigned char  tr_tolower_sbt[1700];
#define TR_TOLOWER_DEFAULT (0)
#define TR_TOLOWER_LITERAL_START (1)
#define TR_TOLOWER_XOR_START (28)
extern UTF_API const co_string_desc tr_tolower_ott[144];

/* utf/tr_toupper.txt: 1552 code points, 68 states, 90 columns */
#define TR_TOUPPER_START_STATE (0)
#define TR_TOUPPER_ACCEPTING_STATES_START (68)
extern UTF_API const unsigned char  tr_toupper_itt[256];
extern UTF_API const unsigned short tr_toupper_sot[68];
extern UTF_API const unsigned short tr_toupper_sbt[1925];
#define TR_TOUPPER_DEFAULT (0)
#define TR_TOUPPER_LITERAL_START (1)
#define TR_TOUPPER_XOR_START (97)
extern UTF_API const co_string_desc tr_toupper_ott[230];

/* utf/tr_totitle.txt: 1529 code points, 68 states, 90 columns */
#define TR_TOTITLE_START_STATE (0)
#define TR_TOTITLE_ACCEPTING_STATES_START (68)
extern UTF_API const unsigned char  tr_totitle_itt[256];
extern UTF_API const unsigned short tr_totitle_sot[68];
extern UTF_API const unsigned short tr_totitle_sbt[1880];
#define TR_TOTITLE_DEFAULT (0)
#define TR_TOTITLE_LITERAL_START (1)
#define TR_TOTITLE_XOR_START (70)
extern UTF_API const co_string_desc tr_totitle_ott[201];

/* utf/tr_foldmatch.txt: 14 code points, 7 states, 11 columns */
#define TR_FOLDMATCH_START_STATE (0)
#define TR_FOLDMATCH_ACCEPTING_STATES_START (7)
extern UTF_API const unsigned char tr_foldmatch_itt[256];
extern UTF_API const unsigned char tr_foldmatch_sot[7];
extern UTF_API const unsigned char tr_foldmatch_sbt[47];
#define TR_FOLDMATCH_DEFAULT (0)
#define TR_FOLDMATCH_LITERAL_START (1)
#define TR_FOLDMATCH_XOR_START (3)
extern UTF_API const co_string_desc tr_foldmatch_ott[3];

/* ---- Width DFA ---- */

/* tr_widths: display column width (0=combining, 1=normal, 2=fullwidth) */
#define TR_WIDTHS_START_STATE (0)
#define TR_WIDTHS_ACCEPTING_STATES_START (373)
extern UTF_API const unsigned char  tr_widths_itt[256];
extern UTF_API const unsigned short tr_widths_sot[373];
extern UTF_API const unsigned short tr_widths_sbt[5707];

/* ---- Grapheme Cluster Break DFA ---- */

#define TR_GCB_START_STATE (0)
#define TR_GCB_ACCEPTING_STATES_START (207)
extern UTF_API const unsigned char  tr_gcb_itt[256];
extern UTF_API const unsigned short tr_gcb_sot[207];
extern UTF_API const unsigned char  tr_gcb_sbt[2914];

/* ---- Extended Pictographic classification DFA ---- */

#define CL_EXTPICT_START_STATE (0)
#define CL_EXTPICT_ACCEPTING_STATES_START (44)
extern UTF_API const unsigned char  cl_extpict_itt[256];
extern UTF_API const unsigned short cl_extpict_sot[44];
extern UTF_API const unsigned char  cl_extpict_sbt[510];

/* ---- Word character classification DFA ----
 *
 * Membership in Alphabetic + Nd + Mn + Mc (see gen/gen_word.pl).  The SBT
 * is unsigned short here rather than unsigned char: 315 states do not fit
 * in a byte.
 */

#define CL_WORD_START_STATE (0)
#define CL_WORD_ACCEPTING_STATES_START (315)
extern UTF_API const unsigned char  cl_word_itt[256];
extern UTF_API const unsigned short cl_word_sot[315];
extern UTF_API const unsigned short cl_word_sbt[4685];

/* ---- NFC normalization DFAs ---- */

/* tr_ccc_nfcqc: Combined CCC + NFC_QC in one DFA.
 * Result encoding: value = ccc * 3 + nfcqc.
 * Decode: ccc = value / 3, nfcqc = value % 3.
 */
#define TR_CCC_NFCQC_START_STATE (0)
#define TR_CCC_NFCQC_ACCEPTING_STATES_START (164)
extern UTF_API const unsigned char  tr_ccc_nfcqc_itt[256];
extern UTF_API const unsigned short tr_ccc_nfcqc_sot[164];
extern UTF_API const unsigned short tr_ccc_nfcqc_sbt[2131];

/* tr_nfd: NFD decomposition */
#define TR_NFD_START_STATE (0)
#define TR_NFD_ACCEPTING_STATES_START (97)
extern UTF_API const unsigned char  tr_nfd_itt[256];
extern UTF_API const unsigned short tr_nfd_sot[97];
extern UTF_API const unsigned short tr_nfd_sbt[3046];
#define TR_NFD_DEFAULT (0)
#define TR_NFD_LITERAL_START (1)
#define TR_NFD_XOR_START (1332)
extern UTF_API const co_string_desc tr_nfd_ott[2045];

/* tr_nfc_compose: NFC composition (pair DFA) */
#define TR_NFC_COMPOSE_START_STATE (0)
#define TR_NFC_COMPOSE_ACCEPTING_STATES_START (1010)
extern UTF_API const unsigned char  tr_nfc_compose_itt[256];
extern UTF_API const unsigned short tr_nfc_compose_sot[1010];
extern UTF_API const unsigned short tr_nfc_compose_sbt[8364];
#define TR_NFC_COMPOSE_NFC_COMPOSE_RESULTS (964)
extern UTF_API const uint32_t tr_nfc_compose_nfc_compose_result[965];

/* ---- DUCET collation (generated by gen/gen_ducet.py; do not edit) ---- */

/* tr_ducet: code point -> CE index; tr_ducet_contract: two code points ->
 * contraction slot (tr_ducet_contract_nfc_compose_result maps it to a CE
 * index).  Each is one pool holding every collator's machine; a collator
 * names its start states.  The START_STATE macros are root's. */
#define TR_DUCET_START_STATE (0)
#define TR_DUCET_ACCEPTING_STATES_START (907)
extern UTF_API const unsigned char  tr_ducet_itt[256];
extern UTF_API const unsigned short tr_ducet_sot[907];
extern UTF_API const unsigned short tr_ducet_sbt[59712];
#define TR_DUCET_CONTRACT_START_STATE (0)
#define TR_DUCET_CONTRACT_ACCEPTING_STATES_START (1224)
extern UTF_API const unsigned char  tr_ducet_contract_itt[256];
extern UTF_API const unsigned short tr_ducet_contract_sot[1224];
extern UTF_API const unsigned short tr_ducet_contract_sbt[12121];
#define TR_DUCET_CONTRACT_NFC_COMPOSE_RESULTS (2142)
extern UTF_API const uint32_t tr_ducet_contract_nfc_compose_result[2143];

/* A CE is a uint32_t:  bits 31-16 primary, bits 15-7 secondary, bits 6-0
 * tertiary.  There is no variable flag; libutf's variable weighting is
 * non-ignorable.  ducet_cetable.c asserts this layout against what the
 * generator packed. */
#define DUCET_CE_PRIMARY_SHIFT   16
#define DUCET_CE_SECONDARY_SHIFT 7
#define DUCET_CE_SECONDARY_MASK  0x1FF
#define DUCET_CE_TERTIARY_MASK   0x7F
#define DUCET_COMMON_SECONDARY   0x0020
#define DUCET_COMMON_TERTIARY    0x02
#define DUCET_CE_SEQUENCES 37430
extern const unsigned short ducet_ce_offset[37432];
extern const uint32_t ducet_ce_weights[];

/* A contraction of three or four code points. */
typedef struct {
    uint32_t cp[4];
    unsigned char n;
    unsigned short ce_index;
} utf_ducet_contraction;

/* [reorder]: primaries in [lo, hi] move by delta. */
typedef struct {
    unsigned short lo, hi;
    short delta;
} utf_ducet_reorder;

#define DUCET_LATIN_LIMIT 0x180
#define UTF_COLLATOR_BACKWARD_SECONDARY 1
#define UTF_COLLATOR_HAS_SETTINGS       2   /* reorder or tertiary_map: the
                                               slow path must apply them */

/* A collator is one locale's view of the shared DUCET tables: where it
 * starts in each DFA, its longer contractions, its Latin fast-path tables
 * (DUCET_LATIN_LIMIT entries each; a code point that can start a
 * contraction has its CE in latin_starter_ce, good only when none follows),
 * and the settings CLDR gives it.  collate.h hands it out as an opaque
 * utf_collator.  utf_collators[0] is root. */
struct utf_collator {
    const char *name;
    int ducet_start;                    /* start state in tr_ducet */
    int contract_start;                 /* start state in tr_ducet_contract */
    unsigned char contract_leads[32];   /* lead bytes that can begin a
                                           contraction, as a bit set; kept
                                           inline, one load from the gate */
    const utf_ducet_contraction *contractions;  /* by cp[0], longest first */
    int n_contractions;
    const uint32_t *latin_ce;
    const uint32_t *latin_starter_ce;
    const utf_ducet_reorder *reorder;   /* [reorder], applied to lead CEs */
    int n_reorder;
    const unsigned char *tertiary_map;  /* [caseFirst upper], or NULL */
    int flags;                          /* UTF_COLLATOR_* */
};
#define UTF_COLLATOR_COUNT 54
extern const struct utf_collator utf_collators[UTF_COLLATOR_COUNT];

/* ---- end of DUCET collation ---- */

/* ---- Charset approximation DFAs ---- */

/* tr_ascii: UTF-8 to ASCII approximation */
#define TR_ASCII_START_STATE (0)
#define TR_ASCII_ACCEPTING_STATES_START (99)
extern UTF_API const unsigned char  tr_ascii_itt[256];
extern UTF_API const unsigned short tr_ascii_sot[99];
extern UTF_API const unsigned char  tr_ascii_sbt[3431];

/* tr_cp437: UTF-8 to CP437 approximation */
#define TR_CP437_START_STATE (0)
#define TR_CP437_ACCEPTING_STATES_START (114)
extern UTF_API const unsigned char  tr_cp437_itt[256];
extern UTF_API const unsigned short tr_cp437_sot[114];
extern UTF_API const unsigned short tr_cp437_sbt[4065];

/* tr_latin1: UTF-8 to ISO-8859-1 approximation */
#define TR_LATIN1_START_STATE (0)
#define TR_LATIN1_ACCEPTING_STATES_START (101)
extern UTF_API const unsigned char  tr_latin1_itt[256];
extern UTF_API const unsigned short tr_latin1_sot[101];
extern UTF_API const unsigned short tr_latin1_sbt[3488];

/* tr_latin2: UTF-8 to ISO-8859-2 approximation */
#define TR_LATIN2_START_STATE (0)
#define TR_LATIN2_ACCEPTING_STATES_START (99)
extern UTF_API const unsigned char  tr_latin2_itt[256];
extern UTF_API const unsigned short tr_latin2_sot[99];
extern UTF_API const unsigned short tr_latin2_sbt[3460];

#ifdef __cplusplus
} /* extern "C" */
#endif

/* ---- Inline DFA runners for case mapping ---- */

static inline const co_string_desc *co_dfa_toupper(const unsigned char *p, int *bXor)
{
    unsigned short iState = TR_TOUPPER_START_STATE;
    do
    {
        unsigned char ch = *p++;
        unsigned char iColumn = tr_toupper_itt[ch];
        unsigned short iOffset = tr_toupper_sot[iState];
        for (;;)
        {
            int y = tr_toupper_sbt[iOffset];
            if (y < 128)
            {
                if (iColumn < y)
                {
                    iState = tr_toupper_sbt[iOffset+1];
                    break;
                }
                else
                {
                    iColumn = (unsigned char)(iColumn - y);
                    iOffset += 2;
                }
            }
            else
            {
                y = 256 - y;
                if (iColumn < y)
                {
                    iState = tr_toupper_sbt[iOffset+iColumn+1];
                    break;
                }
                else
                {
                    iColumn = (unsigned char)(iColumn - y);
                    iOffset = (unsigned short)(iOffset + y + 1);
                }
            }
        }
    } while (iState < TR_TOUPPER_ACCEPTING_STATES_START);

    if (TR_TOUPPER_DEFAULT == iState - TR_TOUPPER_ACCEPTING_STATES_START)
    {
        *bXor = 0;
        return (const co_string_desc *)0;
    }
    else
    {
        *bXor = (TR_TOUPPER_XOR_START <= iState - TR_TOUPPER_ACCEPTING_STATES_START);
        return tr_toupper_ott + iState - TR_TOUPPER_ACCEPTING_STATES_START - 1;
    }
}

static inline const co_string_desc *co_dfa_tolower(const unsigned char *p, int *bXor)
{
    unsigned char iState = TR_TOLOWER_START_STATE;
    do
    {
        unsigned char ch = *p++;
        unsigned char iColumn = tr_tolower_itt[ch];
        unsigned short iOffset = tr_tolower_sot[iState];
        for (;;)
        {
            int y = tr_tolower_sbt[iOffset];
            if (y < 128)
            {
                if (iColumn < y)
                {
                    iState = tr_tolower_sbt[iOffset+1];
                    break;
                }
                else
                {
                    iColumn = (unsigned char)(iColumn - y);
                    iOffset += 2;
                }
            }
            else
            {
                y = 256 - y;
                if (iColumn < y)
                {
                    iState = tr_tolower_sbt[iOffset+iColumn+1];
                    break;
                }
                else
                {
                    iColumn = (unsigned char)(iColumn - y);
                    iOffset = (unsigned short)(iOffset + y + 1);
                }
            }
        }
    } while (iState < TR_TOLOWER_ACCEPTING_STATES_START);

    if (TR_TOLOWER_DEFAULT == iState - TR_TOLOWER_ACCEPTING_STATES_START)
    {
        *bXor = 0;
        return (const co_string_desc *)0;
    }
    else
    {
        *bXor = (TR_TOLOWER_XOR_START <= iState - TR_TOLOWER_ACCEPTING_STATES_START);
        return tr_tolower_ott + iState - TR_TOLOWER_ACCEPTING_STATES_START - 1;
    }
}

static inline const co_string_desc *co_dfa_totitle(const unsigned char *p, int *bXor)
{
    unsigned short iState = TR_TOTITLE_START_STATE;
    do
    {
        unsigned char ch = *p++;
        unsigned char iColumn = tr_totitle_itt[ch];
        unsigned short iOffset = tr_totitle_sot[iState];
        for (;;)
        {
            int y = tr_totitle_sbt[iOffset];
            if (y < 128)
            {
                if (iColumn < y)
                {
                    iState = tr_totitle_sbt[iOffset+1];
                    break;
                }
                else
                {
                    iColumn = (unsigned char)(iColumn - y);
                    iOffset += 2;
                }
            }
            else
            {
                y = 256 - y;
                if (iColumn < y)
                {
                    iState = tr_totitle_sbt[iOffset+iColumn+1];
                    break;
                }
                else
                {
                    iColumn = (unsigned char)(iColumn - y);
                    iOffset = (unsigned short)(iOffset + y + 1);
                }
            }
        }
    } while (iState < TR_TOTITLE_ACCEPTING_STATES_START);

    if (TR_TOTITLE_DEFAULT == iState - TR_TOTITLE_ACCEPTING_STATES_START)
    {
        *bXor = 0;
        return (const co_string_desc *)0;
    }
    else
    {
        *bXor = (TR_TOTITLE_XOR_START <= iState - TR_TOTITLE_ACCEPTING_STATES_START);
        return tr_totitle_ott + iState - TR_TOTITLE_ACCEPTING_STATES_START - 1;
    }
}

static inline const co_string_desc *co_dfa_foldmatch(const unsigned char *p, int *bXor)
{
    int iState = TR_FOLDMATCH_START_STATE;
    do
    {
        unsigned char ch = *p++;
        unsigned char iColumn = tr_foldmatch_itt[ch];
        unsigned short iOffset = tr_foldmatch_sot[iState];
        for (;;)
        {
            int y = tr_foldmatch_sbt[iOffset];
            if (y < 128)
            {
                if (iColumn < y)
                {
                    iState = tr_foldmatch_sbt[iOffset+1];
                    break;
                }
                else
                {
                    iColumn = (unsigned char)(iColumn - y);
                    iOffset += 2;
                }
            }
            else
            {
                y = 256 - y;
                if (iColumn < y)
                {
                    iState = tr_foldmatch_sbt[iOffset+iColumn+1];
                    break;
                }
                else
                {
                    iColumn = (unsigned char)(iColumn - y);
                    iOffset = (unsigned short)(iOffset + y + 1);
                }
            }
        }
    } while (iState < TR_FOLDMATCH_ACCEPTING_STATES_START);

    if (TR_FOLDMATCH_DEFAULT == iState - TR_FOLDMATCH_ACCEPTING_STATES_START)
    {
        *bXor = 0;
        return (const co_string_desc *)0;
    }
    else
    {
        *bXor = (TR_FOLDMATCH_XOR_START <= iState - TR_FOLDMATCH_ACCEPTING_STATES_START);
        return tr_foldmatch_ott + iState - TR_FOLDMATCH_ACCEPTING_STATES_START - 1;
    }
}

#endif /* UTF_TABLES_H */
