/*
 * classify.c — Unicode character classification for UTF-8.
 *
 * The word-character set is a compressed membership DFA generated by
 * gen/classify from gen/data/cl_Word.txt (see gen/gen_word.pl).
 *
 * Unicode 16.0.
 */

#include "utf/classify.h"
#include "utf/utf_tables.h"
#include <stddef.h>

/*
 * Run a membership DFA whose state-branch table is unsigned short.
 *
 * The 315-state word table does not fit the unsigned char SBT format used by
 * the smaller classification tables, so this mirrors RunIntegerDFA_u16 in
 * nfc.c rather than run_dfa in grapheme.c.
 *
 * Stops at the first accepting state.  gen/classify prunes any state whose
 * paths all converge into one accepting state, so acceptance can occur before
 * a code point's final byte; reading on would transition into an unrelated
 * state.  (This is the same trap that corrupted the grapheme tables — see the
 * comment on run_dfa in grapheme.c.)
 */
static int run_membership_dfa_u16(const unsigned char *itt,
                                  const unsigned short *sot,
                                  const unsigned short *sbt,
                                  int start, int accept_start,
                                  const unsigned char *p,
                                  const unsigned char *pEnd)
{
    int iState = start;
    while (p < pEnd && iState < accept_start) {
        unsigned char iColumn = itt[*p++];
        unsigned short iOffset = sot[iState];
        for (;;) {
            int y = sbt[iOffset];
            if (y < 128) {
                if (iColumn < y) { iState = sbt[iOffset + 1]; break; }
                iColumn = (unsigned char)(iColumn - y);
                iOffset = (unsigned short)(iOffset + 2);
            } else {
                y = 256 - y;
                if (iColumn < y) { iState = sbt[iOffset + iColumn + 1]; break; }
                iColumn = (unsigned char)(iColumn - y);
                iOffset = (unsigned short)(iOffset + y + 1);
            }
        }
    }
    return (iState >= accept_start) ? (iState - accept_start) : 0;
}

int utf_is_word(const unsigned char *p, const unsigned char *pEnd)
{
    if (NULL == p || NULL == pEnd || p >= pEnd) return 0;

    return 1 == run_membership_dfa_u16(cl_word_itt, cl_word_sot, cl_word_sbt,
                                       CL_WORD_START_STATE,
                                       CL_WORD_ACCEPTING_STATES_START,
                                       p, pEnd);
}

int utf_is_word_connector(const unsigned char *p, const unsigned char *pEnd)
{
    if (NULL == p || NULL == pEnd || p >= pEnd) return 0;

    /* Ten code points, so a decode-and-compare beats a table.  Matched on
     * the UTF-8 bytes directly to stay consistent with the rest of the
     * library and to avoid decoding a sequence that runs past pEnd. */
    size_t n = (size_t)(pEnd - p);

    /* U+005F LOW LINE */
    if (0x5F == p[0]) return 1;
    if (n < 3) return 0;

    /* U+203F..U+2040 = E2 80 BF..E2 81 80, U+2054 = E2 81 94 */
    if (0xE2 == p[0]) {
        if (0x80 == p[1] && 0xBF == p[2]) return 1;
        if (0x81 == p[1] && (0x80 == p[2] || 0x94 == p[2])) return 1;
        return 0;
    }

    /* U+FE33..U+FE34 = EF B8 B3..EF B8 B4, U+FE4D..U+FE4F = EF B9 8D..8F,
     * U+FF3F = EF BC BF */
    if (0xEF == p[0]) {
        if (0xB8 == p[1] && (0xB3 == p[2] || 0xB4 == p[2])) return 1;
        if (0xB9 == p[1] && 0x8D <= p[2] && p[2] <= 0x8F) return 1;
        if (0xBC == p[1] && 0xBF == p[2]) return 1;
    }
    return 0;
}
